linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  depguard:
    rules:
      main:
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - github.com/tarcisio/infergo
