name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build ./...